#!/bin/bash
#
# This scripts does a basic installation of MrHTTPD.
# You still need to check file locations and permissions for sanity.
#
# MrHTTPD v2.2.0
# Copyright c 2007-2011  Martin Rogge <martin_rogge@users.sourceforge.net>

if [ ! "$id -u" = "0" ]; then
  echo "Further processing is aborted since you are not logged in as user root."
  echo "Please log in as user root and repeat this step."
  echo
  exit 1
fi

. ./mrhttpd.conf
. ./checkconfig

if [ -n "$ERROR" ]; then
  echo "ERROR: There are fatal errors in the configuration file."
  echo "Installation aborted."
  echo
  exit 1
fi

cp -f mrhttpd $BIN_DIR/
if [ -n "$SERVER_DOCS" ]; then
  mkdir -p $SERVER_ROOT$SERVER_DOCS
  cp -u -b html/[2345]*.html $SERVER_ROOT$SERVER_DOCS/
fi
if [ -n "$DOC_DIR" ]; then
  mkdir -p $SERVER_ROOT$DOC_DIR
  cp -u -b html/index.html $SERVER_ROOT$DOC_DIR/
  cp -u -b html/mouse.png $SERVER_ROOT$DOC_DIR/
  if [ -n "$SYSTEM_USER" ]; then
    chown $SYSTEM_USER: $SERVER_ROOT$DOC_DIR
    chown $SYSTEM_USER: $SERVER_ROOT$DOC_DIR/index.html
    chown $SYSTEM_USER: $SERVER_ROOT$DOC_DIR/mouse.png
  fi
fi
if [ -n "$CGI_DIR" ]; then
  mkdir -p $SERVER_ROOT$CGI_DIR
fi
if [ -n "$LOG_FILE" ]; then
  touch $SERVER_ROOT$LOG_FILE
  if [ -n "$SYSTEM_USER" ]; then
    chown $SYSTEM_USER: $SERVER_ROOT$LOG_FILE
  fi
fi




