#!/bin/bash
#
# This scripts builds and pushes Docker images
#
# mrhttpd v2.5.3
# Copyright c 2007-2020  Martin Rogge <martin_rogge@users.sourceforge.net>

set -e

PREFIX=dockahdockah/
SUFFIX=:latest

if [ -f mrhttpd.h ] ; then

	docker build -f docker/Dockerfile -t ${PREFIX}mrhttpd${SUFFIX} .
	docker build -f docker/Dockerfile-put -t ${PREFIX}mrhttpd-put${SUFFIX} .
	docker build -f docker/Dockerfile-fs -t ${PREFIX}mrhttpd-fs${SUFFIX} .

	echo
	echo "-------------"
	echo "Build Success"
	echo "-------------"
	echo

	docker push ${PREFIX}mrhttpd${SUFFIX}
	docker push ${PREFIX}mrhttpd-put${SUFFIX}
	docker push ${PREFIX}mrhttpd-fs${SUFFIX}

	echo
	echo "--------------"
	echo "Upload Success"
	echo "--------------"
	echo

else
	echo "Wrong directory. Nothing done."
fi
