#!/bin/bash
#
# This scripts builds Docker images for the purpose of testing
#
# mrhttpd v2.6.0
# Copyright c 2007-2021  Martin Rogge <martin_rogge@users.sourceforge.net>

set -e

PREFIX=test/
SUFFIX=:test

if [ -f mrhttpd.h ] ; then

	docker build -f docker/Dockerfile -t ${PREFIX}mrhttpd${SUFFIX} .
	docker build -f docker/Dockerfile-fs -t ${PREFIX}mrhttpd-fs${SUFFIX} .
	docker build -f docker/Dockerfile-all -t ${PREFIX}mrhttpd-all${SUFFIX} .

	echo
	echo "-------------"
	echo "Test Success"
	echo "-------------"
	echo

else
	echo "Wrong directory. Nothing done."
fi
